model_name: pspnet
dataset_name: camvid
train_data_path: F:\Resources\dataset\SegNet-Tutorial-master\CamVid\train
train_annot_path: F:\Resources\dataset\SegNet-Tutorial-master\CamVid\trainannot
val_data_path: F:\Resources\dataset\SegNet-Tutorial-master\CamVid\val
val_annot_path: F:\Resources\dataset\SegNet-Tutorial-master\CamVid\valannot

batch_size: 2
optimizer_param: {
      lr: 0.01,
      momentum: 0.9,
      weight_decay: 0.0001
}
iter: 5000
power: 0.9
lr: 0.01
numclass: 12
model_param: {
      numclass: 12
}
pool_core:
  - 1
  - 2
  - 3
  - 6
aux_weight: 0.4
gpus: []
print_freq: 20
save_freq: 30
log_dir: E:\deeper\Xsegment\logs
save_path: E:\deeper\Xsegment\model\
img_size:
  - 400
  - 480